# Netlify configuration for Express.js app
[build]
  command = "npm install && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "22.10.0"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
